name: QuickFarm
main: io.github.toomanybugs1.QuickFarm.Main
version: 1.1
api-version: 1.16
softdepend: [mcMMO]
commands:
    togglequickfarm:
        description: Turns quick farm on or off.
        usage: /togglequickfarm
        permission: QuickFarm.toggle
        permission-message: You don't have permission to change this.